spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: jpa

github:
  client:
    url: https://api.github.com/users